[package]
name = "ntex-redis"
version = "0.3.0-b.1"
authors = ["ntex contributors <team@ntex.rs>"]
description = "Redis client"
documentation = "https://docs.rs/ntex-redis"
repository = "https://github.com/ntex-rs/ntex-redis.git"
categories = ["network-programming"]
keywords = ["ntex", "redis"]
license = "MIT"
exclude = [".gitignore", ".travis.yml", ".cargo/config"]
edition = "2018"

[features]
default = []

# openssl
openssl = ["ntex/openssl"]

# rustls support
rustls = ["ntex/rustls"]

[dependencies]
ntex = "0.5.0-b.2"
itoa = "0.4.5"
btoi = "0.4.2"
log = "0.4"
derive_more = "0.99"

[dev-dependencies]
rand = "0.8"
env_logger = "0.9"

[patch.crates-io]
ntex = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-io = { git = "https://github.com/ntex-rs/ntex.git" }
ntex-tls = { git = "https://github.com/ntex-rs/ntex.git" }
